# Generated by Django 4.0 on 2023-03-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0002_req_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req_room',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
