# Generated by Django 4.0 on 2023-03-12 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0005_remove_req_room_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='req_room',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Tables.room'),
        ),
    ]
