# Generated by Django 4.1.1 on 2023-03-15 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0006_req_room_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=20)),
                ('stu_email', models.EmailField(max_length=200)),
                ('complaint', models.CharField(max_length=500)),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.room')),
            ],
        ),
    ]
